export const GPS_MAX_AGE_MS = 5000
export const GPS_TIMEOUT_MS = 10000
export const DIGIPIN_MATCH_CHARS = 7
export const SPOT_AUTO_CLEAR_HOURS = 48
export const SIGNED_URL_EXPIRY_SECONDS = 3600
export const MAP_ZOOM_LEVEL = 20
export const ORIENTATION_SMOOTHING_ALPHA = 0.15
export const SAVE_SUCCESS_REDIRECT_MS = 2000
